language: go
go:
  - 1.16

jobs:
  include:
    - stage: semantic-release
      deploy:
        provider: script
        cleanup: false
        script: bash semantic-release.sh
        on: 
          branch:
            - main
            - feature/*
